spring:
  datasource:
    url: jdbc:mysql://192.168.0.174:6033/cwenjoy?serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: root
      password: 76750mww

